### ISSUE TITLE
Bad source link

### ISSUE THREAD

**Issue by aleb** [pygobject/pgi-docgen#142]
- Go to http://lazka.github.io/pgi-docs/#GES-1.0/classes/Timeline.html#GES.Timeline.commit
- click [source], notice it takes you to https://cgit.freedesktop.org/gstreamer/gst-editing-services/tree/ges/ges-meta-container.c?h=1.10.2#n3422 but the correct link is https://cgit.freedesktop.org/gstreamer/gst-editing-services/tree/ges/ges-timeline.c?h=1.10.2#n3422 (different filename)

**Comment by lazka** [comment]
Thanks.

**Comment by aleb** [comment]
This seems to be fixed

**Comment by lazka** [comment]
#126 lists some still broken cases. I guess something changed for this function to not hit the bug any more.

Thanks for testing!
