### ISSUE TITLE
Trying to build UDisks documentation

### ISSUE THREAD

**Issue by elboulangero** [pygobject/pgi-docgen#147]
Hi !

I wish to build the doc for `UDisks`. Out of the box, it doesn't work.

    $ ./tools/build.sh UDisks-2.0
    GIR file for UDisks-2.0 not found, aborting.

Somehow I ended up looking in `pgidocgen/girdata/docref/` and I saw a bunch of json files there for different libraries, and I suspect that these are the libraries supported "out of the box".  UDisks is not part of them.

I tried the steps mentioned in "build docs for private libraries". First, I ensured that everything UDisks-related is installed on my machine.

    $ ls /usr/lib/x86_64-linux-gnu/girepository-1.0/ | grep UDisks
    UDisks-2.0.typelib
    $ ls /usr/lib/x86_64-linux-gnu/ | grep udisks
    libudisks2.so.0
    libudisks2.so.0.0.0

Then I tried the command:

    $ GI_TYPELIB_PATH=/usr/lib/x86_64-linux-gnu/girepository-1.0/ \
    LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu \
    ./tools/build.sh UDisks-2.0
    GIR file for UDisks-2.0 not found, aborting.

What do I miss here ? Do I need to install some stuff in the virtual environment ?

**Comment by lazka** [comment]
The files in girdata are optional. You need the .gir file:

```
> sudo apt-file search UDisks-2.0.gir
libudisks2-dev: /usr/share/gir-1.0/UDisks-2.0.gir
> sudo apt install libudisks2-dev
...
```

**Comment by elboulangero** [comment]
Indeed, my mistake. Now it builds without any fuss.

```
$ ./tools/build.sh UDisks-2.0
Gio-2.0: building...
GObject-2.0: building...
UDisks-2.0: building...
Queue build for GObject-2.0
Build started for GObject-2.0
...
UDisks-2.0 finished: 4/4 done
All done
```

Thanks !
