### ISSUE TITLE
UDisks2 links to D-Bus API are broken

### ISSUE THREAD

**Issue by elboulangero** [pygobject/pgi-docgen#148]
Issue
-----

If you have a quick link to [UDisks API Reference](http://storaged.org/doc/udisks2-api/latest), you will see that basically UDisks is made of a D-Bus daemon, and a client library. The library is mainly code generated with `gdbus-codegen`.

Now, if you dive a bit into the doc, you will see that the library documentation always ends up linking to the D-Bus documentation, since this is where the real implementation is.

For example, let's have a look at the [UDisksBlock class](http://storaged.org/doc/udisks2-api/latest/UDisksBlock.html#udisks-block-call-add-configuration-item) from the library.

> Asynchronously invokes the AddConfigurationItem() D-Bus method on proxy .

Clicking on the link `AddConfigurationItem` takes you to the [D-Bus documentation](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-method-org-freedesktop-UDisks2-Block.AddConfigurationItem).

Now, let's compare with the equivalent python documentation for the [Block class](https://lazka.github.io/pgi-docs/UDisks-2.0/classes/Block.html#UDisks.Block.call_add_configuration_item)

> Asynchronously invokes the ‘AddConfigurationItem() [gdbus-method-org-freedesktop-UDisks2-Block.AddConfigurationItem]’ D-Bus method on self

As you can see, the link is broken.

Debugging
----

From now on, commits speak better than words, so you might want to

    git clone https://gitlab.com/arnaud-preevio/pgi-docgen.git
    git checkout art/udisks

It started nicely, but ended up in a mess. Right now I take a break with that. If you have any hint, I'll be happy to rework that and come back with a better result.

Cheers !

**Comment by lazka** [comment]
Those type of manual gtk-doc references are handled through the files in girdata/docref. tools/fetch-docref.py pulls the references from an online gtk-doc instance and the resulting json file then gets used in the doc generation.

**Comment by lazka** [comment]
I've added it in commit aad1c89ddadf510 , but the link you mentioned isn't included. Might be that the script needs an improvement there.. I don't remember the details

**Comment by elboulangero** [comment]
Ok, so that's good news, I've been going in the right direction. What happens after is that the json file generated contains too few references, and lacks all the ones I need. I've been hacking through `tools/fetch-docref.py` to understand why.

It seems that there are two issues to solve.

First, the links toward the UDisks D-Bus API contains dots. For example: <http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-method-org-freedesktop-UDisks2-Block.AddConfigurationItem>. And links with dots are ignored by default, apparently to exclude plenty of irrelevant links.

I worked around that by allowing links with dots, and explicitly blacklisting the links we don't want. It's probably not the right approach, but it works good enough for a start. And it leads us straight into the second problems.

The links I want to keep are ignored anyway because they're part of the `keywords` that were found in the `devhelp2` page, by the function `fetch_pages()`. And this is the part I don't understand. I don't know what are these keywords and why we have to ignore them.


 is that the links contains dots, and there's some code to ignore any link containing dots.

**Comment by lazka** [comment]
Not sure right now. I'd guess I tried to fix #105 without including the world.

**Comment by elboulangero** [comment]
I will experiment a bit more this week and try to come up with something

**Comment by elboulangero** [comment]
Hi, I'm back with some code, clonable and mergable from https://gitlab.com/arnaud-preevio/pgi-docgen.git.

- on branch `art/gdbus-support` you will find improvements to support `gdbus-codegen` generated doc. That's what is needed for UDisks, which relies heavily on gdbus-codegen. With this changes, we go from 433 unresolved links to 0, great ! I'm talking about external links here, links toward the D-Bus Interface documentation, which is only available in the gtk doc, and can't be found in the introspection data.
- on branch `art/print-missed-links` you will find some ugly code that prints the number of unresolved links. This can be useful if you want to see the difference before and after applying the branch mentioned above.
- additionally, and completely unrelated, you can find a few commits on the branch `art/cosmetics`. 

#### More explanation

The changes are not invasive, and only affect the file `pgidocgen/girdata/docref/UDisks-2.0.json`, since it's the only project that uses `gdbus-codegen`.

The changes explicitly target links created by `gdbus-codegen`, after reading [codegen_main.py]( https://git.gnome.org/browse/glib/tree/gio/gdbus-2.0/codegen/codegen_docbook.py) from GLib source code. There you can see the format of the links pointing toward the D-Bus interfaces documentation. These links have a known prefix `gdbus-`, and contain a dot.

It's important to understand that gdbus-codegen generates both the server-side and client-side boilerplate code from an xml definition. The client-side code ends up in a library, and therefore the generated documentation can be found in the introspection. But this client-side library is just a wrapper around the D-Bus interface, and same goes for the documentation: it's just a dummy documentation that points toward the real thing: the D-Bus API documentation. This is the real documentation where things are explained, and it is not part of the introspection. The only place to find it is online.

Locally, if the doc is installed, you find it over there:

    ls /usr/share/gtk-doc/html/udisks2/gdbus-org*

That's it, it's a bit heaby to read, sorry.

Feel free to merge and cherry-pick whatever suits you (please keep my name in the commit if possible, I rely on that for my CV :)

**Comment by lazka** [comment]
Thanks, looks good. I'll have a look later.

**Comment by lazka** [comment]
all pushed as is

**Comment by lazka** [comment]
Updated the online version now. Thanks for improving this.

Can this be closed?

**Comment by elboulangero** [comment]
Yep, I just had a quick look at the online version and it all looks good now. Thanks for taking time with that !
