### ISSUE TITLE
Document Gdk.Rectangle Workaround

### ISSUE THREAD

**Issue by danyeaw** [pygobject/pgi-docgen#151]
In pygtk, gtk.gdk.Rectangle had a valid constructor. The new class is an alias to cario.RectangleInt which doesn't have a compatible GdkRectangle gtype. Currently there is a hacky workaround that is documented in the GNOME Bugzilla here: https://bugzilla.gnome.org/show_bug.cgi?id=735693

class MyRect(Gdk.Rectangle):
    __gtype__ = GObject.type_from_name('GdkRectangle')

I spent hours trying to figure out how to resolve this issue, and it would be great to document in the API for Gdk.Rectangle, and update the IntrospectionPorting Problems section to better explain a valid workaround.

**Comment by lazka** [comment]
The cairo alias was removed in 3.18 if I'm not mistaken.Which gtk version are you using?

**Comment by danyeaw** [comment]
python3-gi is at version 3.20.0. If this was removed in a version, is that documented in the API?

**Comment by lazka** [comment]
And what's your gtk/gdk version? I'm on 3.24 and at least the example in the linked bug report doesn't error out.

Where would you expect it to be documented?

Add a new sub-page with common problems to https://pygobject.readthedocs.io/en/latest/porting.html maybe?

**Comment by danyeaw** [comment]
You are right, it looks like the problem I was running in to was that some definitions in some of my modules were using GdkRectangle and some were using CairoRectangleInt. To answer your question my libgtk-3-0 is at 3.18.9.

So then I guess my request is changing to remove/update the statement in the API that says that "It is identical to cairo.RectangleInt", it is not clear what that means. Identical in which way? That is why I thought there was still an alias and the lack of an explicit creation method made me believe that I had to use CairoRectangleInt.

Speaking of explicit creation, and I can submit a new bug to GNOME Bugzilla, but why doesn't GdkRectangle have explicit object creation (a "new" method) like all of the other classes as described here:
https://wiki.gnome.org/action/show/Projects/PyGObject/InitializerDeprecations

**Comment by lazka** [comment]
> So then I guess my request is changing to remove/update the statement in the API that says that "It is identical to cairo.RectangleInt", it is not clear what that means. Identical in which way? That is why I thought there was still an alias and the lack of an explicit creation method made me believe that I had to use CairoRectangleInt.

The docs are auto generated from C code, identical here means it has the same memory layout. Yeah, not really helpful and confusing with Python..

> Speaking of explicit creation, and I can submit a new bug to GNOME Bugzilla, but why doesn't GdkRectangle have explicit object creation (a "new" method) like all of the other classes as described here:

Because there is no such function on the C level. I guess no one needed it as that type is typically stack allocated in C.

**Comment by danyeaw** [comment]
Thanks for the explanation, I didn't realize the API documentation was autogenerated also. Can we add a note to the Introspection Porting wiki about this?
