### ISSUE TITLE
Generate *.devhelp2 index files, the Devhelp index file format version 1 is deprecated

### ISSUE THREAD

**Issue by ghost** [pygobject/pgi-docgen#166]
Generate *.devhelp2 index files, the Devhelp index file format version 1 is deprecated.

When opening Devhelp from the terminal, there is a warning about the Devhelp index file format version 1 being deprecated, when Devhelp finds and reads such index files.

Unfortunately the format version 2 is not really documented, the best way to learn it is to open a *.devhelp2 file generated by GTK-Doc, for example the one for GLib or GTK+ (or a smaller library to have a smaller example).

**Comment by lazka** [comment]
Thanks.

Our current code generating it is here: https://github.com/pygobject/pgi-docgen/blob/master/pgidocgen/gen/data/ext/devhelp_fork.py
