### ISSUE TITLE
Update GStreamer source links

### ISSUE THREAD

**Issue by aleb** [pygobject/pgi-docgen#174]
For example:
https://cgit.freedesktop.org/gstreamer/gst-editing-services/tree/ges/ges-title-source.c?h=1.14.2#n551
Should be:
https://gitlab.freedesktop.org/gstreamer/gst-editing-services/blob/1.14.2/ges/ges-title-source.c#L551

**Comment by lazka** [comment]
Thanks.

**Comment by lazka** [comment]
Fixed
