### ISSUE TITLE
Missing Libhandy 0.81.0 Widgets

### ISSUE THREAD

**Issue by PizzaLovingNerd** [pygobject/pgi-docgen#194]
It's missing widgets from Libhandy 0.81.0 such as HdyDeck. Most distros haven't packaged Libhandy 0.81.0 yet, but my project is going to use the widgets via subproject.

**Comment by lazka** [comment]
See https://lazka.github.io/pgi-docs/#faq.html

**Comment by lazka** [comment]
In case it wasn't clear, I was referring to "Why is library <XYZ> not included? How can I use library <XYZ> mentioned here, it's not available for my distro?"

I'm sure the package will end up in Debian shortly and then it will automatically show up in the docs.
