### ISSUE TITLE
Documentation for Gtk 4 and Libadwaita.

### ISSUE THREAD

**Issue by MrinmoyHaloi** [pygobject/pgi-docgen#209]
Shouldn't there be documentation for Gtk4 and Libadwaita now ? I haven't found any way to get started with Gtk 4 and libadwaita in python. @lazka

**Comment by MrinmoyHaloi** [comment]
Let me try creating the docs for gtk4. I am on fedora 36 @lazka.

**Comment by MrinmoyHaloi** [comment]
It fails to build. 
"ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)"

**Comment by MrinmoyHaloi** [comment]
I ran `./tools/build.sh Gtk-4.0`. It showed `Gtk-4.0: building...` for sometime.
Then fails to build with the following error
![image](https://user-images.githubusercontent.com/69071143/160152889-e0021b1b-dafc-4857-b53d-f0877607d1f9.png)
@lazka

**Comment by lazka** [comment]
https://lazka.github.io/pgi-docs/#Gtk-4.0 https://lazka.github.io/pgi-docs/#Adw-1
