### ISSUE TITLE
Nautilus 3.0 API appears to have been removed

### ISSUE THREAD

**Issue by dvtate** [pygobject/pgi-docgen#214]
Google still recommends links to the Nautilus 3.0 docs but it appears these pages have been removed?
![image](https://user-images.githubusercontent.com/15305612/234351936-f4c18e57-a50e-4581-a314-0c8d6afed8f7.png)

The 4.0 API appears to still be hosted but it's definitely not the same

**Comment by lazka** [comment]
It was removed from Debian, and the docs include what is in Debian
