### ISSUE TITLE
UDisks-2.0 no longer shows in https://lazka.github.io/pgi-docs

### ISSUE THREAD

**Issue by MestreLion** [pygobject/pgi-docgen#216]
It used to be there 2 months ago, now it is missing... its direct URL was:

https://lazka.github.io/pgi-docs/#UDisks-2.0

Any way to get it back?

(its corresponding Debian/Ubuntu package is `gir1.2-udisks-2.0`, and it is available in latest Ubuntu 23.04)

**Comment by lazka** [comment]
thanks, yeah, some issue with debug data parsing that needs to be investigated.

**Comment by lazka** [comment]
fixed
